# Generated by Django 4.2 on 2023-06-08 06:17

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Reja',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sarlavha', models.CharField(max_length=100)),
                ('matn', models.TextField()),
                ('vaqt', models.DateTimeField(blank=True, null=True)),
                ('holat', models.BooleanField(blank=True, null=True)),
            ],
        ),
    ]
