# Generated by Django 4.2 on 2023-06-08 06:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Asosiy', '0002_alter_reja_vaqt'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reja',
            name='holat',
            field=models.BooleanField(blank=True, choices=[('bajarildi', 'bajarildi'), ('bajarilyapti', 'bajarilyapti')], null=True),
        ),
    ]
