# Generated by Django 4.2 on 2023-06-08 06:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Asosiy', '0003_alter_reja_holat'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reja',
            name='holat',
            field=models.BooleanField(blank=True, null=True),
        ),
    ]
